spring:
  profiles:
    active:
      -dev
---
spring:
  profiles: dev
    application:
      name: cloud-config-center-dev
---
spring:
  profiles: test
    application:
      name: cloud-config-center-test